-- AlterTable
ALTER TABLE "chats" ADD COLUMN     "buyer_last_read_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "seller_last_read_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
